"""Справочник и блюда — первая схема

Ревизия: c54dce852d8d
Предыдущая: нет, это начало
Создана: 2026-09-09

Восемь таблиц: ingredients, ingredient_cards, packaging, cooking_methods,
dishes, dish_components, sync_runs, sync_sheets. Ровно то, что читается из
листов сегодня; конкуренты, дегустации и учётные записи приедут своими
ревизиями.

Чек-лист (его же проверяет агент migration-guard):

  * **downgrade работает.** Прогон upgrade → downgrade → upgrade выполнен
    на боевом Postgres 09.09.2026, закреплён тестом
    `test_migrations_are_reversible`.
  * **Данные не теряются.** Ревизия только создаёт таблицы: терять нечего.
  * **Совместимо со старым кодом.** Совместимость тривиальна: до этой
    ревизии таблиц не было вовсе, и никакой работающий код к ним не
    обращается.
  * **CREATE INDEX CONCURRENTLY не нужен.** Индексы создаются вместе с
    пустыми таблицами, блокировать нечего. Для последующих ревизий на
    живых таблицах это правило вернётся.
  * **У каждого внешнего ключа есть индекс** — Postgres их сам не создаёт,
    и без них «непонятно почему медленно» всплывает через полгода.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c54dce852d8d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cooking_methods",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("legacy_id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("absorption_rate", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("oil_per_100g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cooking_methods_legacy_id"), "cooking_methods", ["legacy_id"], unique=True
    )
    op.create_table(
        "dishes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("legacy_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("price_menu", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("uc_actual", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dishes_category"), "dishes", ["category"], unique=False)
    op.create_index(op.f("ix_dishes_legacy_id"), "dishes", ["legacy_id"], unique=True)
    op.create_index(op.f("ix_dishes_name"), "dishes", ["name"], unique=False)
    op.create_index(op.f("ix_dishes_status"), "dishes", ["status"], unique=False)
    op.create_table(
        "ingredients",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("legacy_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("manufacturer", sa.Text(), nullable=False),
        sa.Column("composition", sa.Text(), nullable=False),
        sa.Column("protein", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("fat", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("carbs", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("kcal", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("price_per_kg", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_per_pack", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("weight_per_piece_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("losses_total", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("losses_unpacking", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("losses_cutting", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("losses_thermal", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_category"), "ingredients", ["category"], unique=False)
    op.create_index(op.f("ix_ingredients_legacy_id"), "ingredients", ["legacy_id"], unique=True)
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=False)
    op.create_index(op.f("ix_ingredients_status"), "ingredients", ["status"], unique=False)
    op.create_index("ix_ingredients_status_name", "ingredients", ["status", "name"], unique=False)
    op.create_table(
        "packaging",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("legacy_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("price_per_piece", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("dish_category", sa.Text(), nullable=False),
        sa.Column("supplier", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packaging_legacy_id"), "packaging", ["legacy_id"], unique=True)
    op.create_index(op.f("ix_packaging_name"), "packaging", ["name"], unique=False)
    op.create_index(op.f("ix_packaging_status"), "packaging", ["status"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_runs_started_at"), "sync_runs", ["started_at"], unique=False)
    op.create_table(
        "dish_components",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dish_id", sa.BigInteger(), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), nullable=True),
        sa.Column("packaging_id", sa.BigInteger(), nullable=True),
        sa.Column("cooking_method_id", sa.BigInteger(), nullable=True),
        sa.Column("net_weight_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("row_type", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("row_type in ('main', 'packaging')", name="ck_dish_components_row_type"),
        sa.CheckConstraint(
            "(ingredient_id is not null) <> (packaging_id is not null)",
            name="ck_dish_components_one_target",
        ),
        sa.ForeignKeyConstraint(["cooking_method_id"], ["cooking_methods.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dish_id"], ["dishes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["packaging_id"], ["packaging.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dish_components_cooking_method_id"),
        "dish_components",
        ["cooking_method_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dish_components_dish_id"), "dish_components", ["dish_id"], unique=False
    )
    op.create_index(
        op.f("ix_dish_components_ingredient_id"), "dish_components", ["ingredient_id"], unique=False
    )
    op.create_index(
        op.f("ix_dish_components_packaging_id"), "dish_components", ["packaging_id"], unique=False
    )
    op.create_table(
        "ingredient_cards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("label_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("manufacturer", sa.Text(), nullable=False),
        sa.Column("supplier", sa.Text(), nullable=False),
        sa.Column("composition", sa.Text(), nullable=False),
        sa.Column("protein", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("fat", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("carbs", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("kcal", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("shelf_life_sealed", sa.Text(), nullable=False),
        sa.Column("shelf_life_defrost", sa.Text(), nullable=False),
        sa.Column("shelf_life_after", sa.Text(), nullable=False),
        sa.Column("defrost_conditions", sa.Text(), nullable=False),
        sa.Column("label_url", sa.Text(), nullable=False),
        sa.Column("package_url", sa.Text(), nullable=False),
        sa.Column("before_url", sa.Text(), nullable=False),
        sa.Column("after_url", sa.Text(), nullable=False),
        sa.Column("declaration", sa.Text(), nullable=False),
        sa.Column("halal_certificate", sa.Text(), nullable=False),
        sa.Column("approval_status", sa.Text(), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), nullable=True),
        sa.Column("link_status", sa.String(length=16), nullable=False),
        sa.Column("link_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "link_status <> 'linked' or ingredient_id is not null",
            name="ck_ingredient_cards_linked_has_ingredient",
        ),
        sa.CheckConstraint(
            "link_status in ('linked', 'ambiguous', 'candidate', 'orphan')",
            name="ck_ingredient_cards_link_status",
        ),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingredient_cards_ingredient_id"),
        "ingredient_cards",
        ["ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredient_cards_link_status"), "ingredient_cards", ["link_status"], unique=False
    )
    op.create_index(op.f("ix_ingredient_cards_name"), "ingredient_cards", ["name"], unique=False)
    op.create_table(
        "sync_sheets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("spreadsheet", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("header_issues", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["sync_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "spreadsheet", "title"),
    )
    op.create_index(op.f("ix_sync_sheets_run_id"), "sync_sheets", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_sheets_run_id"), table_name="sync_sheets")
    op.drop_table("sync_sheets")
    op.drop_index(op.f("ix_ingredient_cards_name"), table_name="ingredient_cards")
    op.drop_index(op.f("ix_ingredient_cards_link_status"), table_name="ingredient_cards")
    op.drop_index(op.f("ix_ingredient_cards_ingredient_id"), table_name="ingredient_cards")
    op.drop_table("ingredient_cards")
    op.drop_index(op.f("ix_dish_components_packaging_id"), table_name="dish_components")
    op.drop_index(op.f("ix_dish_components_ingredient_id"), table_name="dish_components")
    op.drop_index(op.f("ix_dish_components_dish_id"), table_name="dish_components")
    op.drop_index(op.f("ix_dish_components_cooking_method_id"), table_name="dish_components")
    op.drop_table("dish_components")
    op.drop_index(op.f("ix_sync_runs_started_at"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_packaging_status"), table_name="packaging")
    op.drop_index(op.f("ix_packaging_name"), table_name="packaging")
    op.drop_index(op.f("ix_packaging_legacy_id"), table_name="packaging")
    op.drop_table("packaging")
    op.drop_index("ix_ingredients_status_name", table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_status"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_legacy_id"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_category"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_dishes_status"), table_name="dishes")
    op.drop_index(op.f("ix_dishes_name"), table_name="dishes")
    op.drop_index(op.f("ix_dishes_legacy_id"), table_name="dishes")
    op.drop_index(op.f("ix_dishes_category"), table_name="dishes")
    op.drop_table("dishes")
    op.drop_index(op.f("ix_cooking_methods_legacy_id"), table_name="cooking_methods")
    op.drop_table("cooking_methods")
    # ### end Alembic commands ###
