"""Профили и роли

Ревизия: см. ниже
Создана: 2026-09-10

Три таблицы: profiles, roles, user_roles.

Учётки, пароли и сессии ведёт Supabase Auth в схеме `auth`; своих таблиц
под них не заводим. Здесь только предметная область: как человека зовут и
что ему можно.

Связь с `auth.users` по идентификатору, но БЕЗ внешнего ключа. Схема
`auth` принадлежит GoTrue, и ограничения из наших миграций на неё — способ
однажды не пережить его обновление.

Чек-лист (его же проверяет агент migration-guard):

  * **downgrade работает.** Ревизия только создаёт таблицы и наполняет
    справочник ролей; откат сносит их целиком.
  * **Данные не теряются.** Терять нечего: таблиц до этой ревизии не было.
  * **Совместимо со старым кодом.** Существующий код к этим таблицам не
    обращается — ручки, которым они нужны, появляются в этом же коммите.
  * **CREATE INDEX CONCURRENTLY не нужен.** Индексы создаются вместе с
    пустыми таблицами, блокировать нечего.
  * **У внешних ключей есть индексы.** `user_roles.profile_id` покрыт
    первичным ключом, `role_code` — отдельным индексом.

Роли наполняются прямо здесь: это фиксированный справочник из четырёх
значений, а не пользовательские данные. Отдельный скрипт заполнения для
такого — лишняя деталь, о которой однажды забудут.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d2ff156b9bb"
down_revision: str | None = "c54dce852d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_email"), "profiles", ["email"], unique=True)
    op.create_index(op.f("ix_profiles_is_active"), "profiles", ["is_active"], unique=False)
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "user_roles",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_code"], ["roles.code"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("profile_id", "role_code"),
    )
    op.create_index("ix_user_roles_role_code", "user_roles", ["role_code"], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        sa.table(
            "roles",
            sa.column("code", sa.String),
            sa.column("title", sa.Text),
            sa.column("description", sa.Text),
        ),
        [
            {
                "code": "chef",
                "title": "Бренд-шеф",
                "description": "Справочник, блюда, ТТК, решения по склейке.",
            },
            {
                "code": "cook",
                "title": "Повар",
                "description": "Карточки ингредиентов: заполнение и фото.",
            },
            {
                "code": "commerce",
                "title": "Коммерческий отдел",
                "description": "Расчётка: назначение продажных цен.",
            },
            {
                "code": "developer",
                "title": "Разработчик",
                "description": "Всё, включая служебные разделы.",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_roles_role_code", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_profiles_is_active"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_email"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
